# Generated by Django 3.2.3 on 2021-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
