# Generated by Django 3.2.3 on 2021-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(default=None, verbose_name='Prix'),
        ),
    ]
