# Generated by Django 3.2.3 on 2021-05-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AddField(
            model_name='article',
            name='total_number_of_purchase',
            field=models.IntegerField(default=0, verbose_name="Nombre d'achat total"),
        ),
    ]
