# Generated by Django 3.2.3 on 2021-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210517_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_on', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='created_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='articles.Category'),
        ),
    ]
