# Generated by Django 3.2.3 on 2021-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='price',
            field=models.FloatField(default=None, verbose_name='Prix'),
        ),
    ]
