# Generated by Django 3.2.3 on 2021-05-18 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_panier_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatedorder',
            name='price',
            field=models.FloatField(default=None, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='validatedorder',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
    ]
