# Generated by Django 3.2.3 on 2021-05-18 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210517_1357'),
        ('commandes', '0004_auto_20210518_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validatedorder',
            old_name='price',
            new_name='tot_price',
        ),
        migrations.RenameField(
            model_name='validatedorder',
            old_name='quantity',
            new_name='tot_quantity',
        ),
        migrations.RemoveField(
            model_name='validatedorder',
            name='articles',
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('price', models.FloatField(default=None, verbose_name='Prix')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_article', to='articles.article')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='commandes.validatedorder')),
            ],
        ),
        migrations.AddField(
            model_name='validatedorder',
            name='articles',
            field=models.ManyToManyField(related_name='order_articles', through='commandes.LigneCommande', to='articles.Article'),
        ),
    ]
