# Generated by Django 3.2.3 on 2021-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0005_auto_20210518_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatedorder',
            name='reduction',
            field=models.BooleanField(default=False),
        ),
    ]
