# Generated by Django 3.2.3 on 2021-05-20 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_validatedorder_reduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatedorder',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
