# Generated by Django 3.2.3 on 2021-06-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_thumbnail'),
        ('commandes', '0007_alter_validatedorder_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_article', to='articles.article'),
        ),
    ]
