# Generated by Django 3.2.3 on 2021-06-06 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_alter_lignecommande_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatedorder',
            name='tot_price',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='validatedorder',
            name='tot_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité'),
        ),
    ]
