# Generated by Django 3.2.3 on 2021-05-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210516_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
