# Generated by Django 3.2.3 on 2021-05-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210518_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Nom', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='Prénom', max_length=100, verbose_name='Prénom'),
        ),
    ]
